version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on: 
        - db

  db:
    image: mariadb:latest
    volumes:
      - .docker/volumes/mariadb/data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - ./.env.docker