version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
    depends_on: 
        - db

  db:
    image: mariadb:latest
    volumes:
      - .docker/volumes/mariadb/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}