export const ARTICLE_REPOSITORY_TOKEN = 'ARTICLE_REPOSITORY_TOKEN';
export const AUTHOR_REPOSITORY_TOKEN = 'AUTHOR_REPOSITORY_TOKEN';
export const TAGS_REPOSITORY_TOKEN = 'TAGS_REPOSITORY_TOKEN';
export const CATEGORIES_REPOSITORY_TOKEN = 'CATEGORIES_REPOSITORY_TOKEN';
