# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    env:
      ENVIRONMENT: production
      PORT: 3000
      DATABASE_USER: admin
      DATABASE_PASSWORD: supers3cr3t
      DATABASE_HOST: database-1.cr44s2400fte.eu-central-1.rds.amazonaws.com
      DATABASE_ROOT_PASSWORD: supers3cr3t
      DATABASE_NAME: tourin
      DATABASE_PORT: 3306
      DATABASE_MIGRATION: false
      DATABASE_MIGRATION_FILES: 'dist/migrations/*'
      PROD_ENV_FILE: ${{ secrets.TOURIN_PRODUCTION }}

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        DATABASE_USER: "123456abcdef"
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_HOST: database-1.cr44s2400fte.eu-central-1.rds.amazonaws.com
    - run: touch .env
    - run: echo "${{secrets.TOURIN_PRODUCTION }}" > .env
    - run: echo DATABASE_HOST="database-1.cr44s2400fte.eu-central-1.rds.amazonaws.com" >> .env
    - run: yarn install
    - run: yarn build
    - run: pm2 restart tourin-api
